name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    # runs-on: macOS-latest
    runs-on: macos-13

    steps:
    # - uses: swift-actions/setup-swift@v1
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: switch xcode
      run: sudo xcode-select -s '/Applications/Xcode_15.0.app/Contents/Developer'

    - name: use cache
      id: cache
      uses: actions/cache@v2
      with:
        path: |
          xcfs/.build
          Frameworks/ios_system/xcfs/.build
        key: ${{ runner.os }}-${{ hashFiles('get_frameworks.sh', 'xcfs/Package.swift') }}

    - name: get frameworks
      if: steps.cache.outputs.cache-hit != 'true'
      run: ./get_frameworks.sh

    - name: copy xcconfig
      run: cp template_setup.xcconfig developer_setup.xcconfig

    - name: BlinkTests
      run: xcodebuild -project Blink.xcodeproj -scheme BlinkTests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPad Air (5th generation)' test | xcpretty

    - name: actual build
      run: set -o pipefail && xcodebuild archive -project Blink.xcodeproj -scheme Blink -sdk iphoneos -configuration Debug clean build IPHONEOS_DEPLOYMENT_TARGET='16.1' CODE_SIGN_IDENTITY='' CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO ONLY_ACTIVE_ARCH=NO | tee build.log | xcpretty

    - name: generate unsigned debug ipa
      run: |
        cd ~
        mkdir Payload
        mv ~/Library/Developer/Xcode/Archives/*/*/Products/Applications/Blink.app ~/Payload/
        zip -r Blink.ipa Payload
    - name: upload ipa
      uses: actions/upload-artifact@v4
      with:
        name: 'BlinkShell2'
        path: ~/Blink.ipa
